name: physio_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  get: 4.5.1
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: 5.2.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  lottie: ^1.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/
